[package]
name = "allegro-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "allegro_cwr"
path = "src/lib.rs"

[[bin]]
name = "allegro"
path = "src/main.rs"

[dependencies]
rusqlite = { version = "0.35.0", features = ["bundled"] }
