[workspace]
members = [
    "crates/allegro_cwr_derive",
    "crates/allegro_cwr_sqlite",
    "crates/allegro_cwr_json",
    "crates/allegro_cwr",
    "crates/allegro",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"