//! ISO 639-2 Language Dialect codes lookup table

use once_cell::sync::Lazy;
use std::collections::HashMap;

/// ISO 639-2 Language Dialect codes mapping
pub static LANGUAGE_DIALECT_CODES: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert("AAR", "Afar");
    m.insert("ABK", "Abkhazian");
    m.insert("ACE", "Achinese");
    m.insert("ACH", "Acoli");
    m.insert("ADA", "Adangme");
    m.insert("ADY", "Adyghe; Adygei");
    m.insert("AFA", "Afro-Asiatic languages");
    m.insert("AFH", "Afrihili");
    m.insert("AFR", "Afrikaans");
    m.insert("AIN", "Ainu");
    m.insert("AKA", "Akan");
    m.insert("AKK", "Akkadian");
    m.insert("ALB", "Albanian");
    m.insert("SQI", "Albanian");
    m.insert("ALE", "Aleut");
    m.insert("ALG", "Algonquian languages");
    m.insert("ALT", "Southern Altai");
    m.insert("AMH", "Amharic");
    m.insert("ANG", "English, Old (ca.450-1100)");
    m.insert("ANP", "Angika");
    m.insert("APA", "Apache languages");
    m.insert("ARA", "Arabic");
    m.insert("ARC", "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)");
    m.insert("ARG", "Aragonese");
    m.insert("ARM", "Armenian");
    m.insert("HYE", "Armenian");
    m.insert("ARN", "Mapudungun; Mapuche");
    m.insert("ARP", "Arapaho");
    m.insert("ART", "Artificial languages");
    m.insert("ARW", "Arawak");
    m.insert("ASM", "Assamese");
    m.insert("AST", "Asturian; Bable; Leonese; Asturleonese");
    m.insert("ATH", "Athapascan languages");
    m.insert("AUS", "Australian languages");
    m.insert("AVA", "Avaric");
    m.insert("AVE", "Avestan");
    m.insert("AWA", "Awadhi");
    m.insert("AYM", "Aymara");
    m.insert("AZE", "Azerbaijani");
    m.insert("BAD", "Banda languages");
    m.insert("BAI", "Bamileke languages");
    m.insert("BAK", "Bashkir");
    m.insert("BAL", "Baluchi");
    m.insert("BAM", "Bambara");
    m.insert("BAN", "Balinese");
    m.insert("BAQ", "Basque");
    m.insert("EUS", "Basque");
    m.insert("BAS", "Basa");
    m.insert("BAT", "Baltic languages");
    m.insert("BEJ", "Beja; Bedawiyet");
    m.insert("BEL", "Belarusian");
    m.insert("BEM", "Bemba");
    m.insert("BEN", "Bengali");
    m.insert("BER", "Berber languages");
    m.insert("BHO", "Bhojpuri");
    m.insert("BIH", "Bihari languages");
    m.insert("BIK", "Bikol");
    m.insert("BIN", "Bini; Edo");
    m.insert("BIS", "Bislama");
    m.insert("BLA", "Siksika");
    m.insert("BNT", "Bantu languages");
    m.insert("TIB", "Tibetan");
    m.insert("BOD", "Tibetan");
    m.insert("BOS", "Bosnian");
    m.insert("BRA", "Braj");
    m.insert("BRE", "Breton");
    m.insert("BTK", "Batak languages");
    m.insert("BUA", "Buriat");
    m.insert("BUG", "Buginese");
    m.insert("BUL", "Bulgarian");
    m.insert("BUR", "Burmese");
    m.insert("MYA", "Burmese");
    m.insert("BYN", "Blin; Bilin");
    m.insert("CAD", "Caddo");
    m.insert("CAI", "Central American Indian languages");
    m.insert("CAR", "Galibi Carib");
    m.insert("CAT", "Catalan; Valencian");
    m.insert("CAU", "Caucasian languages");
    m.insert("CEB", "Cebuano");
    m.insert("CEL", "Celtic languages");
    m.insert("CZE", "Czech");
    m.insert("CES", "Czech");
    m.insert("CHA", "Chamorro");
    m.insert("CHB", "Chibcha");
    m.insert("CHE", "Chechen");
    m.insert("CHG", "Chagatai");
    m.insert("CHI", "Chinese");
    m.insert("ZHO", "Chinese");
    m.insert("CHK", "Chuukese");
    m.insert("CHM", "Mari");
    m.insert("CHN", "Chinook jargon");
    m.insert("CHO", "Choctaw");
    m.insert("CHP", "Chipewyan; Dene Suline");
    m.insert("CHR", "Cherokee");
    m.insert("CHU", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic");
    m.insert("CHV", "Chuvash");
    m.insert("CHY", "Cheyenne");
    m.insert("CMC", "Chamic languages");
    m.insert("CNR", "Montenegrin");
    m.insert("COP", "Coptic");
    m.insert("COR", "Cornish");
    m.insert("COS", "Corsican");
    m.insert("CPE", "Creoles and pidgins, English based");
    m.insert("CPF", "Creoles and pidgins, French-based");
    m.insert("CPP", "Creoles and pidgins, Portuguese-based");
    m.insert("CRE", "Cree");
    m.insert("CRH", "Crimean Tatar; Crimean Turkish");
    m.insert("CRP", "Creoles and pidgins");
    m.insert("CSB", "Kashubian");
    m.insert("CUS", "Cushitic languages");
    m.insert("WEL", "Welsh");
    m.insert("CYM", "Welsh");
    m.insert("DAK", "Dakota");
    m.insert("DAN", "Danish");
    m.insert("DAR", "Dargwa");
    m.insert("DAY", "Land Dayak languages");
    m.insert("DEL", "Delaware");
    m.insert("DEN", "Slave (Athapascan)");
    m.insert("GER", "German");
    m.insert("DEU", "German");
    m.insert("DGR", "Dogrib");
    m.insert("DIN", "Dinka");
    m.insert("DIV", "Divehi; Dhivehi; Maldivian");
    m.insert("DOI", "Dogri");
    m.insert("DRA", "Dravidian languages");
    m.insert("DSB", "Lower Sorbian");
    m.insert("DUA", "Duala");
    m.insert("DUM", "Dutch, Middle (ca.1050-1350)");
    m.insert("DUT", "Dutch; Flemish");
    m.insert("NLD", "Dutch; Flemish");
    m.insert("DYU", "Dyula");
    m.insert("DZO", "Dzongkha");
    m.insert("EFI", "Efik");
    m.insert("EGY", "Egyptian (Ancient)");
    m.insert("EKA", "Ekajuk");
    m.insert("GRE", "Greek, Modern (1453-)");
    m.insert("ELL", "Greek, Modern (1453-)");
    m.insert("ELX", "Elamite");
    m.insert("ENG", "English");
    m.insert("ENM", "English, Middle (1100-1500)");
    m.insert("EPO", "Esperanto");
    m.insert("EST", "Estonian");
    m.insert("EWE", "Ewe");
    m.insert("EWO", "Ewondo");
    m.insert("FAN", "Fang");
    m.insert("FAO", "Faroese");
    m.insert("PER", "Persian");
    m.insert("FAS", "Persian");
    m.insert("FAT", "Fanti");
    m.insert("FIJ", "Fijian");
    m.insert("FIL", "Filipino; Pilipino");
    m.insert("FIN", "Finnish");
    m.insert("FIU", "Finno-Ugrian languages");
    m.insert("FON", "Fon");
    m.insert("FRE", "French");
    m.insert("FRA", "French");
    m.insert("FRM", "French, Middle (ca.1400-1600)");
    m.insert("FRO", "French, Old (842-ca.1400)");
    m.insert("FRR", "Northern Frisian");
    m.insert("FRS", "Eastern Frisian");
    m.insert("FRY", "Western Frisian");
    m.insert("FUL", "Fulah");
    m.insert("FUR", "Friulian");
    m.insert("GAA", "Ga");
    m.insert("GAY", "Gayo");
    m.insert("GBA", "Gbaya");
    m.insert("GEM", "Germanic languages");
    m.insert("GEO", "Georgian");
    m.insert("KAT", "Georgian");
    m.insert("GEZ", "Geez");
    m.insert("GIL", "Gilbertese");
    m.insert("GLA", "Gaelic; Scottish Gaelic");
    m.insert("GLE", "Irish");
    m.insert("GLG", "Galician");
    m.insert("GLV", "Manx");
    m.insert("GMH", "German, Middle High (ca.1050-1500)");
    m.insert("GOH", "German, Old High (ca.750-1050)");
    m.insert("GON", "Gondi");
    m.insert("GOR", "Gorontalo");
    m.insert("GOT", "Gothic");
    m.insert("GRB", "Grebo");
    m.insert("GRC", "Greek, Ancient (to 1453)");
    m.insert("GRN", "Guarani");
    m.insert("GSW", "Swiss German; Alemannic; Alsatian");
    m.insert("GUJ", "Gujarati");
    m.insert("GWI", "Gwich'in");
    m.insert("HAI", "Haida");
    m.insert("HAT", "Haitian; Haitian Creole");
    m.insert("HAU", "Hausa");
    m.insert("HAW", "Hawaiian");
    m.insert("HEB", "Hebrew");
    m.insert("HER", "Herero");
    m.insert("HIL", "Hiligaynon");
    m.insert("HIM", "Himachali languages; Western Pahari languages");
    m.insert("HIN", "Hindi");
    m.insert("HIT", "Hittite");
    m.insert("HMN", "Hmong; Mong");
    m.insert("HMO", "Hiri Motu");
    m.insert("HRV", "Croatian");
    m.insert("HSB", "Upper Sorbian");
    m.insert("HUN", "Hungarian");
    m.insert("HUP", "Hupa");
    m.insert("IBA", "Iban");
    m.insert("IBO", "Igbo");
    m.insert("ICE", "Icelandic");
    m.insert("ISL", "Icelandic");
    m.insert("IDO", "Ido");
    m.insert("III", "Sichuan Yi; Nuosu");
    m.insert("IJO", "Ijo languages");
    m.insert("IKU", "Inuktitut");
    m.insert("ILE", "Interlingue; Occidental");
    m.insert("ILO", "Iloko");
    m.insert("INA", "Interlingua (International Auxiliary Language Association)");
    m.insert("INC", "Indic languages");
    m.insert("IND", "Indonesian");
    m.insert("INE", "Indo-European languages");
    m.insert("INH", "Ingush");
    m.insert("IPK", "Inupiaq");
    m.insert("IRA", "Iranian languages");
    m.insert("IRO", "Iroquoian languages");
    m.insert("ITA", "Italian");
    m.insert("JAV", "Javanese");
    m.insert("JBO", "Lojban");
    m.insert("JPN", "Japanese");
    m.insert("JPR", "Judeo-Persian");
    m.insert("JRB", "Judeo-Arabic");
    m.insert("KAA", "Kara-Kalpak");
    m.insert("KAB", "Kabyle");
    m.insert("KAC", "Kachin; Jingpho");
    m.insert("KAL", "Kalaallisut; Greenlandic");
    m.insert("KAM", "Kamba");
    m.insert("KAN", "Kannada");
    m.insert("KAR", "Karen languages");
    m.insert("KAS", "Kashmiri");
    m.insert("KAU", "Kanuri");
    m.insert("KAW", "Kawi");
    m.insert("KAZ", "Kazakh");
    m.insert("KBD", "Kabardian");
    m.insert("KHA", "Khasi");
    m.insert("KHI", "Khoisan languages");
    m.insert("KHM", "Central Khmer");
    m.insert("KHO", "Khotanese; Sakan");
    m.insert("KIK", "Kikuyu; Gikuyu");
    m.insert("KIN", "Kinyarwanda");
    m.insert("KIR", "Kirghiz; Kyrgyz");
    m.insert("KMB", "Kimbundu");
    m.insert("KOK", "Konkani");
    m.insert("KOM", "Komi");
    m.insert("KON", "Kongo");
    m.insert("KOR", "Korean");
    m.insert("KOS", "Kosraean");
    m.insert("KPE", "Kpelle");
    m.insert("KRC", "Karachay-Balkar");
    m.insert("KRL", "Karelian");
    m.insert("KRO", "Kru languages");
    m.insert("KRU", "Kurukh");
    m.insert("KUA", "Kuanyama; Kwanyama");
    m.insert("KUM", "Kumyk");
    m.insert("KUR", "Kurdish");
    m.insert("KUT", "Kutenai");
    m.insert("LAD", "Ladino");
    m.insert("LAH", "Lahnda");
    m.insert("LAM", "Lamba");
    m.insert("LAO", "Lao");
    m.insert("LAT", "Latin");
    m.insert("LAV", "Latvian");
    m.insert("LEZ", "Lezghian");
    m.insert("LIM", "Limburgan; Limburger; Limburgish");
    m.insert("LIN", "Lingala");
    m.insert("LIT", "Lithuanian");
    m.insert("LOL", "Mongo");
    m.insert("LOZ", "Lozi");
    m.insert("LTZ", "Luxembourgish; Letzeburgesch");
    m.insert("LUA", "Luba-Lulua");
    m.insert("LUB", "Luba-Katanga");
    m.insert("LUG", "Ganda");
    m.insert("LUI", "Luiseno");
    m.insert("LUN", "Lunda");
    m.insert("LUO", "Luo (Kenya and Tanzania)");
    m.insert("LUS", "Lushai");
    m.insert("MAC", "Macedonian");
    m.insert("MKD", "Macedonian");
    m.insert("MAD", "Madurese");
    m.insert("MAG", "Magahi");
    m.insert("MAH", "Marshallese");
    m.insert("MAI", "Maithili");
    m.insert("MAK", "Makasar");
    m.insert("MAL", "Malayalam");
    m.insert("MAN", "Mandingo");
    m.insert("MAO", "Maori");
    m.insert("MRI", "Maori");
    m.insert("MAP", "Austronesian languages");
    m.insert("MAR", "Marathi");
    m.insert("MAS", "Masai");
    m.insert("MAY", "Malay");
    m.insert("MSA", "Malay");
    m.insert("MDF", "Moksha");
    m.insert("MDR", "Mandar");
    m.insert("MEN", "Mende");
    m.insert("MGA", "Irish, Middle (900-1200)");
    m.insert("MIC", "Mi'kmaq; Micmac");
    m.insert("MIN", "Minangkabau");
    m.insert("MIS", "Uncoded languages");
    m.insert("MKH", "Mon-Khmer languages");
    m.insert("MLG", "Malagasy");
    m.insert("MLT", "Maltese");
    m.insert("MNC", "Manchu");
    m.insert("MNI", "Manipuri");
    m.insert("MNO", "Manobo languages");
    m.insert("MOH", "Mohawk");
    m.insert("MON", "Mongolian");
    m.insert("MOS", "Mossi");
    m.insert("MUL", "Multiple languages");
    m.insert("MUN", "Munda languages");
    m.insert("MUS", "Creek");
    m.insert("MWL", "Mirandese");
    m.insert("MWR", "Marwari");
    m.insert("MYN", "Mayan languages");
    m.insert("MYV", "Erzya");
    m.insert("NAH", "Nahuatl languages");
    m.insert("NAI", "North American Indian languages");
    m.insert("NAP", "Neapolitan");
    m.insert("NAU", "Nauru");
    m.insert("NAV", "Navajo; Navaho");
    m.insert("NBL", "Ndebele, South; South Ndebele");
    m.insert("NDE", "Ndebele, North; North Ndebele");
    m.insert("NDO", "Ndonga");
    m.insert("NDS", "Low German; Low Saxon; German, Low; Saxon, Low");
    m.insert("NEP", "Nepali");
    m.insert("NEW", "Nepal Bhasa; Newari");
    m.insert("NIA", "Nias");
    m.insert("NIC", "Niger-Kordofanian languages");
    m.insert("NIU", "Niuean");
    m.insert("NNO", "Norwegian Nynorsk; Nynorsk, Norwegian");
    m.insert("NOB", "Bokmål, Norwegian; Norwegian Bokmål");
    m.insert("NOG", "Nogai");
    m.insert("NON", "Norse, Old");
    m.insert("NOR", "Norwegian");
    m.insert("NQO", "N'Ko");
    m.insert("NSO", "Pedi; Sepedi; Northern Sotho");
    m.insert("NUB", "Nubian languages");
    m.insert("NWC", "Classical Newari; Old Newari; Classical Nepal Bhasa");
    m.insert("NYA", "Chichewa; Chewa; Nyanja");
    m.insert("NYM", "Nyamwezi");
    m.insert("NYN", "Nyankole");
    m.insert("NYO", "Nyoro");
    m.insert("NZI", "Nzima");
    m.insert("OCI", "Occitan (post 1500)");
    m.insert("OJI", "Ojibwa");
    m.insert("ORI", "Oriya");
    m.insert("ORM", "Oromo");
    m.insert("OSA", "Osage");
    m.insert("OSS", "Ossetian; Ossetic");
    m.insert("OTA", "Turkish, Ottoman (1500-1928)");
    m.insert("OTO", "Otomian languages");
    m.insert("PAA", "Papuan languages");
    m.insert("PAG", "Pangasinan");
    m.insert("PAL", "Pahlavi");
    m.insert("PAM", "Pampanga; Kapampangan");
    m.insert("PAN", "Panjabi; Punjabi");
    m.insert("PAP", "Papiamento");
    m.insert("PAU", "Palauan");
    m.insert("PEO", "Persian, Old (ca.600-400 B.C.)");
    m.insert("PHI", "Philippine languages");
    m.insert("PHN", "Phoenician");
    m.insert("PLI", "Pali");
    m.insert("POL", "Polish");
    m.insert("PON", "Pohnpeian");
    m.insert("POR", "Portuguese");
    m.insert("PRA", "Prakrit languages");
    m.insert("PRO", "Provençal, Old (to 1500); Occitan, Old (to 1500)");
    m.insert("PUS", "Pushto; Pashto");
    m.insert("QUE", "Quechua");
    m.insert("RAJ", "Rajasthani");
    m.insert("RAP", "Rapanui");
    m.insert("RAR", "Rarotongan; Cook Islands Maori");
    m.insert("ROA", "Romance languages");
    m.insert("ROH", "Romansh");
    m.insert("ROM", "Romany");
    m.insert("RUM", "Romanian; Moldavian; Moldovan");
    m.insert("RON", "Romanian; Moldavian; Moldovan");
    m.insert("RUN", "Rundi");
    m.insert("RUP", "Aromanian; Arumanian; Macedo-Romanian");
    m.insert("RUS", "Russian");
    m.insert("SAD", "Sandawe");
    m.insert("SAG", "Sango");
    m.insert("SAH", "Yakut");
    m.insert("SAI", "South American Indian languages");
    m.insert("SAL", "Salishan languages");
    m.insert("SAM", "Samaritan Aramaic");
    m.insert("SAN", "Sanskrit");
    m.insert("SAS", "Sasak");
    m.insert("SAT", "Santali");
    m.insert("SCN", "Sicilian");
    m.insert("SCO", "Scots");
    m.insert("SEL", "Selkup");
    m.insert("SEM", "Semitic languages");
    m.insert("SGA", "Irish, Old (to 900)");
    m.insert("SGN", "Sign Languages");
    m.insert("SHN", "Shan");
    m.insert("SID", "Sidamo");
    m.insert("SIN", "Sinhala; Sinhalese");
    m.insert("SIO", "Siouan languages");
    m.insert("SIT", "Sino-Tibetan languages");
    m.insert("SLA", "Slavic languages");
    m.insert("SLO", "Slovak");
    m.insert("SLK", "Slovak");
    m.insert("SLV", "Slovenian");
    m.insert("SMA", "Southern Sami");
    m.insert("SME", "Northern Sami");
    m.insert("SMI", "Sami languages");
    m.insert("SMJ", "Lule Sami");
    m.insert("SMN", "Inari Sami");
    m.insert("SMO", "Samoan");
    m.insert("SMS", "Skolt Sami");
    m.insert("SNA", "Shona");
    m.insert("SND", "Sindhi");
    m.insert("SNK", "Soninke");
    m.insert("SOG", "Sogdian");
    m.insert("SOM", "Somali");
    m.insert("SON", "Songhai languages");
    m.insert("SOT", "Sotho, Southern");
    m.insert("SPA", "Spanish; Castilian");
    m.insert("SRD", "Sardinian");
    m.insert("SRN", "Sranan Tongo");
    m.insert("SRP", "Serbian");
    m.insert("SRR", "Serer");
    m.insert("SSA", "Nilo-Saharan languages");
    m.insert("SSW", "Swati");
    m.insert("SUK", "Sukuma");
    m.insert("SUN", "Sundanese");
    m.insert("SUS", "Susu");
    m.insert("SUX", "Sumerian");
    m.insert("SWA", "Swahili");
    m.insert("SWE", "Swedish");
    m.insert("SYC", "Classical Syriac");
    m.insert("SYR", "Syriac");
    m.insert("TAH", "Tahitian");
    m.insert("TAI", "Tai languages");
    m.insert("TAM", "Tamil");
    m.insert("TAT", "Tatar");
    m.insert("TEL", "Telugu");
    m.insert("TEM", "Timne");
    m.insert("TER", "Tereno");
    m.insert("TET", "Tetum");
    m.insert("TGK", "Tajik");
    m.insert("TGL", "Tagalog");
    m.insert("THA", "Thai");
    m.insert("TIG", "Tigre");
    m.insert("TIR", "Tigrinya");
    m.insert("TIV", "Tiv");
    m.insert("TKL", "Tokelau");
    m.insert("TLH", "Klingon; tlhIngan-Hol");
    m.insert("TLI", "Tlingit");
    m.insert("TMH", "Tamashek");
    m.insert("TOG", "Tonga (Nyasa)");
    m.insert("TON", "Tonga (Tonga Islands)");
    m.insert("TPI", "Tok Pisin");
    m.insert("TSI", "Tsimshian");
    m.insert("TSN", "Tswana");
    m.insert("TSO", "Tsonga");
    m.insert("TUK", "Turkmen");
    m.insert("TUM", "Tumbuka");
    m.insert("TUP", "Tupi languages");
    m.insert("TUR", "Turkish");
    m.insert("TUT", "Altaic languages");
    m.insert("TVL", "Tuvalu");
    m.insert("TWI", "Twi");
    m.insert("TYV", "Tuvinian");
    m.insert("UDM", "Udmurt");
    m.insert("UGA", "Ugaritic");
    m.insert("UIG", "Uighur; Uyghur");
    m.insert("UKR", "Ukrainian");
    m.insert("UMB", "Umbundu");
    m.insert("UND", "Undetermined");
    m.insert("URD", "Urdu");
    m.insert("UZB", "Uzbek");
    m.insert("VAI", "Vai");
    m.insert("VEN", "Venda");
    m.insert("VIE", "Vietnamese");
    m.insert("VOL", "Volapük");
    m.insert("VOT", "Votic");
    m.insert("WAK", "Wakashan languages");
    m.insert("WAL", "Wolaitta; Wolaytta");
    m.insert("WAR", "Waray");
    m.insert("WAS", "Washo");
    m.insert("WEN", "Sorbian languages");
    m.insert("WLN", "Walloon");
    m.insert("WOL", "Wolof");
    m.insert("XAL", "Kalmyk; Oirat");
    m.insert("XHO", "Xhosa");
    m.insert("YAO", "Yao");
    m.insert("YAP", "Yapese");
    m.insert("YID", "Yiddish");
    m.insert("YOR", "Yoruba");
    m.insert("YPK", "Yupik languages");
    m.insert("ZAP", "Zapotec");
    m.insert("ZBL", "Blissymbols; Blissymbolics; Bliss");
    m.insert("ZEN", "Zenaga");
    m.insert("ZGH", "Standard Moroccan Tamazight");
    m.insert("ZHA", "Zhuang; Chuang");
    m.insert("ZND", "Zande languages");
    m.insert("ZUL", "Zulu");
    m.insert("ZUN", "Zuni");
    m.insert("ZXX", "No linguistic content; Not applicable");
    m.insert("ZZA", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki");
    m
});

/// Validates an ISO 639-2 language dialect code
pub fn is_valid_language_dialect_code(code: &str) -> bool {
    LANGUAGE_DIALECT_CODES.contains_key(code)
}

/// Gets the description for an ISO 639-2 language dialect code
pub fn get_language_dialect_description(code: &str) -> Option<&'static str> {
    LANGUAGE_DIALECT_CODES.get(code).copied()
}

/// Gets all valid ISO 639-2 language dialect codes
pub fn get_all_language_dialect_codes() -> Vec<&'static str> {
    LANGUAGE_DIALECT_CODES.keys().copied().collect()
}
