//! Society members lookup table with transmitter codes

use once_cell::sync::Lazy;
use std::collections::HashMap;

/// Society member transmitter codes mapping
pub static SOCIETY_TRANSMITTER_CODES: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert("0", "DP");
    m.insert("0000", "ALL RECIPIENTS");
    m.insert("1", "ACUM");
    m.insert("10", "ASCAP");
    m.insert("101", "SOCAN");
    m.insert("102", "NASCAM");
    m.insert("103", "ACDAM");
    m.insert("104", "Royal Flame Music Gmbh");
    m.insert("105", "MASA");
    m.insert("106", "COMPASS");
    m.insert("107", "ACAM");
    m.insert("108", "CHA");
    m.insert("109", "KCI");
    m.insert("11", "AUSTRO-MECHANA");
    m.insert("110", "LATGA-A");
    m.insert("111", "HDS-ZAMP");
    m.insert("112", "SAZAS");
    m.insert("113", "LAA");
    m.insert("114", "AGAYC");
    m.insert("115", "UCMR-ADA");
    m.insert("116", "EAU");
    m.insert("117", "MESAM");
    m.insert("118", "KOMCA");
    m.insert("119", "MCSC");
    m.insert("12", "AMCOS");
    m.insert("120", "LIRA");
    m.insert("121", "VDFS");
    m.insert("122", "AKKA/LAA");
    m.insert("123", "COSGA");
    m.insert("124", "COSOMA");
    m.insert("125", "BNDA");
    m.insert("126", "MCT");
    m.insert("127", "ALBAUTOR");
    m.insert("128", "IMRO");
    m.insert("129", "SOBODAYCOM");
    m.insert("13", "AWA");
    m.insert("130", "BUTODRA");
    m.insert("131", "SADA");
    m.insert("132", "BILD-KUNST");
    m.insert("133", "ZAMCOPS");
    m.insert("134", "SLPRS");
    m.insert("135", "SADH");
    m.insert("136", "ZAMP");
    m.insert("137", "SOFAM");
    m.insert("138", "KOPIOSTO");
    m.insert("139", "COPY-DAN BILLEDKUNST");
    m.insert("14", "ARGENTORES");
    m.insert("140", "UACRR");
    m.insert("141", "ATN");
    m.insert("142", "DALRO");
    m.insert("143", "TEATERAUTOR");
    m.insert("144", "HAA");
    m.insert("145", "DPRS");
    m.insert("146", "SPAC");
    m.insert("147", "FILMAUTOR");
    m.insert("148", "ADAGP");
    m.insert("149", "ARS");
    m.insert("15", "APA");
    m.insert("150", "BEELDRECHT");
    m.insert("151", "BONO");
    m.insert("152", "BUS");
    m.insert("153", "DACS");
    m.insert("154", "HUNGART");
    m.insert("155", "SOMAAP");
    m.insert("156", "VAGA");
    m.insert("157", "VBK");
    m.insert("158", "VEGAP");
    m.insert("159", "VISCOPY");
    m.insert("16", "BUMDA");
    m.insert("160", "RUPIS");
    m.insert("161", "MUST");
    m.insert("162", "AMPAL");
    m.insert("163", "APG-JAPAN");
    m.insert("164", "APSAV");
    m.insert("166", "ABRAC");
    m.insert("167", "ABRAMUS");
    m.insert("168", "ACCESS");
    m.insert("169", "ANACIM");
    m.insert("17", "AMRA");
    m.insert("170", "ARMAUTHOR");
    m.insert("171", "ASDAC");
    m.insert("172", "ASSIM");
    m.insert("173", "ATIDA");
    m.insert("174", "ATN");
    m.insert("175", "AUTORARTE");
    m.insert("176", "AWGACS");
    m.insert("177", "BURAFO");
    m.insert("178", "CAL");
    m.insert("179", "COPYRO");
    m.insert("18", "BGDA");
    m.insert("180", "COSCAP");
    m.insert("181", "CPSN");
    m.insert("182", "CREAIMAGEN");
    m.insert("183", "CSCS");
    m.insert("184", "DGA");
    m.insert("185", "DIRECTORES");
    m.insert("186", "DRCC");
    m.insert("187", "FLIM JUS");
    m.insert("188", "FONOPERU");
    m.insert("189", "HMS");
    m.insert("19", "BMDA");
    m.insert("190", "JACAP");
    m.insert("191", "KAZAK");
    m.insert("192", "KOSA");
    m.insert("193", "KUVASTO");
    m.insert("194", "KYRGYZPATENT");
    m.insert("195", "MSG");
    m.insert("196", "MUSIKEDITION");
    m.insert("197", "NMPA");
    m.insert("198", "PAPPRI");
    m.insert("199", "SABEM");
    m.insert("2", "ADDAF");
    m.insert("20", "SODRAC");
    m.insert("200", "SACK");
    m.insert("201", "SARTEC");
    m.insert("202", "SAS");
    m.insert("203", "SESAM");
    m.insert("204", "SFF");
    m.insert("205", "SGA");
    m.insert("206", "SGDL");
    m.insert("207", "SNAC");
    m.insert("208", "SOCIETE DE L’IMAGE");
    m.insert("209", "SOCINPRO");
    m.insert("21", "BMI");
    m.insert("210", "SODART");
    m.insert("211", "SOPE");
    m.insert("212", "SPACQ");
    m.insert("213", "SQN");
    m.insert("214", "SUOMEN KIRJAILIJALIITTO");
    m.insert("215", "THE AUTHOR'S REGISTRY INC.");
    m.insert("216", "THE SOCIETY OF AUTHORS");
    m.insert("217", "UFFICIO LEGALE");
    m.insert("218", "VEVAM");
    m.insert("219", "WGA");
    m.insert("22", "MCSN");
    m.insert("220", "WGJ");
    m.insert("221", "ZAMP");
    m.insert("222", "ZAPA");
    m.insert("223", "COSOTA");
    m.insert("224", "SOMAS");
    m.insert("225", "SAIF");
    m.insert("226", "AACIMH");
    m.insert("227", "SGACEDOM");
    m.insert("228", "ROMS");
    m.insert("229", "ICG");
    m.insert("22D", "Les Editions Du 22 Decembre");
    m.insert("23", "BUMA");
    m.insert("230", "ADAVIS");
    m.insert("231", "AUTVIS");
    m.insert("232", "GESTOR");
    m.insert("233", "SACEMLUXEMBOURG");
    m.insert("234", "UCOSO");
    m.insert("235", "SACENC");
    m.insert("24", "BURIDA");
    m.insert("25", "BSDA");
    m.insert("26", "CASH");
    m.insert("27", "CAPAC");
    m.insert("28", "LITA");
    m.insert("29", "SCD");
    m.insert("3", "AEPI");
    m.insert("30", "AMAR");
    m.insert("300", "WID CENTRE");
    m.insert("301", "GESAC");
    m.insert("302", "LATINAUTOR");
    m.insert("303", "NORD-DOC");
    m.insert("304", "SONGCODE");
    m.insert("305", "IMJV");
    m.insert("306", "CCL");
    m.insert("307", "MISASIA");
    m.insert("308", "ECAD");
    m.insert("309", "LATINNET");
    m.insert("31", "DILIA");
    m.insert("310", "DIVA");
    m.insert("319", "ICE");
    m.insert("32", "FILSCAP");
    m.insert("33", "OMDA");
    m.insert("34", "HARRY FOX AGENCY");
    m.insert("35", "GEMA");
    m.insert("36", "IPRS");
    m.insert("37", "BUBEDRA");
    m.insert("38", "JASRAC");
    m.insert("39", "MUSICAUTOR");
    m.insert("4", "AGADU");
    m.insert("40", "KODA");
    m.insert("41", "LITERAR-MECHANA");
    m.insert("42", "LVG");
    m.insert("43", "MCSK");
    m.insert("44", "MCPS");
    m.insert("45", "BBDA");
    m.insert("46", "MRS");
    m.insert("47", "BCDA");
    m.insert("48", "NCB");
    m.insert("49", "ONDA");
    m.insert("4AD", "4AD Music Limited");
    m.insert("5", "AKM");
    m.insert("50", "OSA");
    m.insert("51", "PROLITTERIS");
    m.insert("52", "PRS");
    m.insert("53", "PROCAN");
    m.insert("54", "ALCS");
    m.insert("55", "SABAM");
    m.insert("56", "SACD");
    m.insert("57", "SACERAU");
    m.insert("58", "SACEM");
    m.insert("59", "SACM");
    m.insert("6", "BUCUDA");
    m.insert("60", "SACVEN");
    m.insert("61", "SADAIC");
    m.insert("62", "SADEMBRA");
    m.insert("63", "SAMRO");
    m.insert("64", "SOKOJ");
    m.insert("65", "SAYCE");
    m.insert("66", "SBACEM");
    m.insert("67", "SBAT");
    m.insert("68", "SDRM (SDRM should no longer be used. Please use SACEM 058 instead)");
    m.insert("69", "SPA");
    m.insert("7", "APDAYC");
    m.insert("70", "SOGEM");
    m.insert("71", "SESAC");
    m.insert("72", "SGAE");
    m.insert("73", "SCAM");
    m.insert("74", "SIAE");
    m.insert("75", "SUISSIMAGE");
    m.insert("76", "ACEMLA");
    m.insert("77", "STEF");
    m.insert("78", "STEMRA");
    m.insert("79", "STIM");
    m.insert("8", "APRA");
    m.insert("80", "SUISA");
    m.insert("81", "SARRAL");
    m.insert("82", "OTPDA");
    m.insert("83", "SONECA");
    m.insert("84", "SAYCO");
    m.insert("85", "SOZA");
    m.insert("86", "SICAM");
    m.insert("87", "SPACEMF");
    m.insert("88", "CMRRA");
    m.insert("89", "TEOSTO");
    m.insert("9", "ARTISJUS");
    m.insert("90", "TONO");
    m.insert("91", "SSA");
    m.insert("92", "SOCINADA");
    m.insert("93", "UBC");
    m.insert("94", "RAO");
    m.insert("95", "VG WORT");
    m.insert("96", "COTT");
    m.insert("97", "ZAIKS");
    m.insert("98", "ZIMRA");
    m.insert("99", "NS");
    m.insert("AAL", "Ceg Rights Usa");
    m.insert("AB", "Altitude Balloon");
    m.insert("ABO", "ABOOD MUSIC LIMITED");
    m.insert("AC", "Almo Music of Canada");
    m.insert("ACC", "Accorder Music Publishing Ltd");
    m.insert("ACM", "Galleryac Music");
    m.insert("ACT", "ACTIVE MUSIC PUBLISHING PTY L");
    m.insert("AE", "HTV MUSIC");
    m.insert("AEM", "Arcadia Entertainment Muzik Ve Belgesel Pazarlama Ltd Sti");
    m.insert("AFR", "Boom Sky Trade Pty Ltd");
    m.insert("AIR", "AIRSTATE LTD");
    m.insert("ALF", "Allforone Music Sarl");
    m.insert("ALL", "ALL RECIPIENTS");
    m.insert("ALP", "Alpha Music Publishing Uk Limited");
    m.insert("ALV", "Alvaro Music Bv");
    m.insert("AM", "Almo Music Corporation");
    m.insert("AME", "AME MUSIKVERLAG EDWARD KASSNER GMBH");
    m.insert("AMG", "Atlas Music Group");
    m.insert("AML", "Alibi Music Library Limited");
    m.insert("AMP", "Songs Of The Blomerati");
    m.insert("AP", "Associated Production Music");
    m.insert("APL", "Apollo Music");
    m.insert("APO", "Aporetic Music Publishing");
    m.insert("ARC", "Arcadia (Msi)");
    m.insert("ARM", "Annie Reed Music Ltd");
    m.insert("ART", "Discovering Arts Music Group Edition");
    m.insert("ASM", "Grow Your Own Music");
    m.insert("ATP", "At Publishing");
    m.insert("AUM", "Audiomicro Publishing");
    m.insert("AUN", "Audio Network Plc");
    m.insert("AVE", "Avenue Editorial Suisse");
    m.insert("AVI", "Another Victory Inc");
    m.insert("AX", "Alliance Audiosparx");
    m.insert("BAI", "Bailer Music Publishing Limited");
    m.insert("BB", "Bridge Building Music Inc");
    m.insert("BBM", "Big Branch Music Inc");
    m.insert("BEC", "Because Editions");
    m.insert("BG", "BMG");
    m.insert("BGM", "Big Music Machine");
    m.insert("BHI", "Boosey And Hawkes Inc");
    m.insert("BHM", "Boosey-And-Hawkes-Music-Publ- Ltd");
    m.insert("BIX", "Bixio Music Group Ltd");
    m.insert("BK", "Bucks Music Limited");
    m.insert("BL", "BUG MUSIC LIMITED");
    m.insert("BLT", "Belletulipe Sa");
    m.insert("BM", "The Bicycle Music Company");
    m.insert("BMC", "BLUEWATER MUSIC CORP");
    m.insert("BMM", "BLUE MOUNTAIN MUSIC LTD");
    m.insert("BMP", "Bailers Music Publishing");
    m.insert("BN", "BLOC NOTES ED");
    m.insert("BNH", "Business Nieuws Holding Bv");
    m.insert("BNO", "Bno Publishing");
    m.insert("BON", "Bonnier Music Publishing");
    m.insert("BRE", "Want A Fresh One Music");
    m.insert("BRM", "Ricordi E C Spa");
    m.insert("BS", "Broon Songs Gmbh & Co. Kg");
    m.insert("BU", "BUG MUSIC, INC.");
    m.insert("BUD", "Rolf Budde Musikverlag Gmbh");
    m.insert("BUX", "Bucks Music Italia Srl");
    m.insert("CAF", "Cafe Concerto S R L");
    m.insert("CAN", "Candid Music Publishing Limited");
    m.insert("CAR", "Carlin Music Corp");
    m.insert("CAS", "Copyright Administration Services Limited");
    m.insert("CAV", "Cavendish-Music-Co-Ltd");
    m.insert("CBE", "Quarrington Worthy Music");
    m.insert("CC", "Cam Cine TV Music Inc");
    m.insert("CCH", "Campbell Connelly Holland Bv");
    m.insert("CCS", "Ccs Rights Management Corp I");
    m.insert("CDC", "EDITORA COMPANIA COLOMBIANA DE DISCOS S A");
    m.insert("CEG", "Ceg Rights B.V.");
    m.insert("CEN", "Centricity Songs");
    m.insert("CEZ", "Cezame Music Uk Limited");
    m.insert("CH", "Cherry Lane");
    m.insert("CHO", "Chrysalis One Sweden");
    m.insert("CHR", "CHRYSALIS SONGS BENELUX");
    m.insert("CIN", "Cafe' Concerto International S");
    m.insert("CIT", "Cafe' Concerto Italia Ed Mus");
    m.insert("CL9", "Cloud 9 Holland Music Publishing");
    m.insert("CMI", "Conexion Music Limited");
    m.insert("CMP", "Casablanca Media Publishing Inc");
    m.insert("CMS", "Compact Music Services Ltd");
    m.insert("CN", "Copyright.Net");
    m.insert("COL", "COLLECT MUSIC PUBLISHERS BV");
    m.insert("COM", "Compact Collections Ltd");
    m.insert("CON", "Conexion Music Limited");
    m.insert("COR", "Corbeau Publishing Scandinavia Ab");
    m.insert("CPI", "Copyright Power International B V");
    m.insert("CPM", "CP MASTERS BELGIUM");
    m.insert("CPS", "Cp Masters Scandinavia");
    m.insert("CRI", "Criskos Music");
    m.insert("CRO", "CROSSROAD PUBLISHING");
    m.insert("CTH", "Carthage Music Limited");
    m.insert("CTM", "CTM Entertainment Belgium");
    m.insert("CVA", "CV America Music");
    m.insert("CVP", "Cooking Vinyl Publishing");
    m.insert("CWW", "C2w Music Ltd");
    m.insert("D6M", "District 6 Music Publishing Limited");
    m.insert("DAV", "David Media");
    m.insert("DEF", "Defensive Music Ltd");
    m.insert("DEM", "Deep East Music Ltd");
    m.insert("DEN", "Dennis Music International Ltd");
    m.insert("DHM", "Dan Hodges Publishing Llc");
    m.insert("DHP", "Hodges House Of Songwriters");
    m.insert("DJP", "Dj Publishing");
    m.insert("DM", "Dne Music Publishing Limited");
    m.insert("DML", "Dennis Music Limited (Gb)");
    m.insert("DMP", "Dreamer Music Publishing Cc");
    m.insert("DNA", "Dna Musik Gmbh");
    m.insert("DNM", "22d Music Netherlands");
    m.insert("DO", "Doorn Music Publishing");
    m.insert("DOD", "Do Diese Editions");
    m.insert("DOM", "DOMINO PUBLISHING COMPANY SCANDINAVIA");
    m.insert("DOW", "Downtown Dmp Songs");
    m.insert("DP", "DiPiuSRL");
    m.insert("DRS", "Sauter Dr Musikverlag Gmbh");
    m.insert("DSC", "Discovery Trademark Holding");
    m.insert("DT", "DISCOVERY TRADEMARK HOLDING COMPANY INC");
    m.insert("DTN", "Downtown Music Benelux");
    m.insert("DUC", "DUCHAMP INCD/B/A");
    m.insert("EAT", "Eaton Music Ltd");
    m.insert("ECM", "Encore Merci");
    m.insert("EDA", "Editorial Avenue");
    m.insert("EDB", "Edition Bjorlund");
    m.insert("EIM", "Downtown Music Uk Limited");
    m.insert("EMC", "EMI CHRISTIAN MUSIC PUBLISHING");
    m.insert("EMI", "EMI MUSIC PUBLISHING LTD");
    m.insert("EMO", "Emp Elements Music Publishing");
    m.insert("EMP", "So Essential Tunes");
    m.insert("EMS", "European Media Support (Ems) Bv");
    m.insert("END", "ENDEMOL MUSIC NEDERLAND");
    m.insert("EP", "Epm Online");
    m.insert("EPM", "Ep Music Limited");
    m.insert("ERA", "Next Era");
    m.insert("ETE", "Easy Tempo Europe Sl");
    m.insert("ETM", "E T Music Publishing");
    m.insert("ETT", "Easy Tempo Too");
    m.insert("EXH", "Exhibeo Publishing");
    m.insert("EXT", "THE EXTREME MUSIC LIBRARY LTD");
    m.insert("FA", "Famous Music Corporation");
    m.insert("FAN", "Fanfan Music Liechti & Cie");
    m.insert("FAR", "Farrell Music Limited");
    m.insert("FBM", "Freibank Musikverlage Mark Chung E. K.");
    m.insert("FC", "Firstcom");
    m.insert("FCM", "Faircloud Music");
    m.insert("FCU", "Final Cue Music Library");
    m.insert("FCW", "Fc Walvisch Bv");
    m.insert("FIN", "FINTAGE PUBLISHING AND COLLECTION B.V.");
    m.insert("FIV", "Engine Co 35 Music Publishing");
    m.insert("FLE", "Frederic Leibovitz Editeur");
    m.insert("FME", "Fm Entretenimiento Sas");
    m.insert("FMG", "Fairwood Music (Germany) Gmbh");
    m.insert("FMI", "Firstworks Music International Limited");
    m.insert("FMO", "Final Mix Online Cc");
    m.insert("FOO", "411 Publishing Company 20");
    m.insert("FRM", "Frog Music");
    m.insert("FWD", "Fairwood Music Ltd");
    m.insert("FWI", "Fairwood Music Italia Srl");
    m.insert("FWM", "FIREWORKS MUSIC LTD");
    m.insert("FX", "FOX");
    m.insert("FXF", "Fox Fuse Llc");
    m.insert("G7M", "G 7 Music");
    m.insert("GBH", "BOTE BOCK DER BOOSEY HAWKES BOTE BOCK GMBH CO EDITION");
    m.insert("GGM", "Greengate Media");
    m.insert("GIS", "Gismonti Edition");
    m.insert("GJM", "Gerard Et Jerome Music");
    m.insert("GLM", "Gl Music A/S");
    m.insert("GOT", "Good-Tunes-Music Ag");
    m.insert("GP", "GIA Publications Inc.");
    m.insert("GRE", "GREENSLEEVES PUBLISHING LIMITED");
    m.insert("GRF", "Gelfand Rennert & Feldman Publishing");
    m.insert("GSA", "Good Sounds Amsterdam Publishing Bv");
    m.insert("GTP", "Songs Of Global Entertainment");
    m.insert("GbhMC", "Galileo Music Communication G");
    m.insert("HAC", "Hacate Scandinavia");
    m.insert("HB", "HORNALL BROTHERS MUSIC");
    m.insert("HF", "Harry Fox");
    m.insert("HFM", "High Fashion Music Bv");
    m.insert("HKM", "PAPA'S MUSIC BV");
    m.insert("HM", "Horus Music");
    m.insert("HOH", "Songs in the House of Hassle");
    m.insert("HOT", "Hot Streak Music B.V.");
    m.insert("HSP", "Shout! Music Publishing Uk");
    m.insert("HTE", "HTE");
    m.insert("HWG", "Have We Got Music For You");
    m.insert("IDM", "IDM MUSIC LTD");
    m.insert("IG", "THE INTERNATIONAL MUSIC NETWORK LTD");
    m.insert("IM", "IMRAS");
    m.insert("IMA", "SONGS OF IMAGEM MUSIC");
    m.insert("IMG", "Editions Img Liechti Et Cie");
    m.insert("IMP", "Ingrooves");
    m.insert("INT", "Interzone Music Publishing Ltd");
    m.insert("IVX", "Intervox Production Music Publishing Gmbh");
    m.insert("JAN", "JANMAR MUSIC");
    m.insert("JPM", "Jingle Punks Music");
    m.insert("JRM", "JACK RUSSELL MUSIC LIMITED");
    m.insert("KAP", "KASSNER ASSOCIATED PUBLISHERS LIMITED");
    m.insert("KCM", "Keep Clear Music Limited");
    m.insert("KEW", "Kew Music B.V.");
    m.insert("KITAELD SIRKETI", "KALAN MUZIK FILM VE YAYIM LI");
    m.insert("KM", "Kobalt Songs Music Publishing");
    m.insert("KOB", "KOBALT MUSIC PUBLISHING LTD (KMP)");
    m.insert("KVN", "KVN PUBLISHING PTY LTD");
    m.insert("KWM", "Kingsway Music");
    m.insert("KYR", "Know Your Rights");
    m.insert("LAL", "Little Assembly Limited");
    m.insert("LBM", "Little Brother Music Inc");
    m.insert("LGD", "Le Grand Divertissement B.V.");
    m.insert("LIO", "LIONHEART MUSIC AB");
    m.insert("LOR", "Lorenz Corporation The");
    m.insert("LPH", "London Publishing House");
    m.insert("LXE", "Lx-Editora-Lda");
    m.insert("MA", "Musicallstars Bv");
    m.insert("MAC", "Macloud Bv");
    m.insert("MAG", "Magic Arts Publishing Usa");
    m.insert("MAK", "Make Sense");
    m.insert("MAM", "Songs Of Mam");
    m.insert("MAR", "Mars Music Scandinavia");
    m.insert("MAS", "Masstrax Music Net");
    m.insert("MBT", "Music By Tafari Inc");
    m.insert("MCH", "Muziekuitgeverij Chrijoe");
    m.insert("MCM", "Mike Curb Music");
    m.insert("MCS", "MCS MUSIC LIMITED");
    m.insert("MD", "Musicdirector Bv");
    m.insert("MDM", "Mummy Dust Music Ltd");
    m.insert("MG", "UNIVERSAL MUSIC PUBLISHING INTERNATIONAL LTD");
    m.insert("MGM", "More Me Gusta Music");
    m.insert("MGT", "Jrm Music");
    m.insert("MI", "Music And Images Gmbh");
    m.insert("MIS", "Misty Music Ab");
    m.insert("ML", "Music Sales LTD");
    m.insert("MLG", "SCION THREE MUSIC LLC");
    m.insert("MLM", "Missing Link Music Llc");
    m.insert("MMG", "Mmghq Ltd.");
    m.insert("MMP", "Machiavelli Music Publishing");
    m.insert("MND", "MEDIAN MUZIK EDISYON LIMITED SIRKETI");
    m.insert("MNF", "MEDIAN MUSIC INTERNATIONAL");
    m.insert("MO", "MONCUR STREET MUSIC LTD");
    m.insert("MOM", "Music Of The Mothership");
    m.insert("MON", "Mondiamusic");
    m.insert("MOT", "Motus Music Limited");
    m.insert("MPL", "Mpl Communications Ltd");
    m.insert("MPW", "Zavitson Music");
    m.insert("MS", "Music Sales Corporation / Embassy");
    m.insert("MSH", "MUSHROOM MUSIC PTY LTD");
    m.insert("MSI", "Msi Music Administration");
    m.insert("MSO", "Musinfo Les Editions");
    m.insert("MSV", "Massive Publishing Bv");
    m.insert("MT", "Megatrax Music");
    m.insert("MU", "Universal Music Corp.");
    m.insert("MUS", "Mute Song");
    m.insert("MWL", "Musiqware Ltd");
    m.insert("MYM", "Mymusicrights Publishing");
    m.insert("MZK", "Muzikal Productions Entertainment Volkan Guecer");
    m.insert("NAN", "Nanada B V");
    m.insert("NCM", "No Copyright Music");
    m.insert("NET", "NETTWERK SONGS PUBLISHING LTD");
    m.insert("NMC", "Nuovi Media & Comunicazione Srl");
    m.insert("NMG", "Nada Music Gmbh");
    m.insert("NOR", "Nordton Edition");
    m.insert("NTM", "Native Tongue Music Publishing");
    m.insert("NWC", "Nw Collections");
    m.insert("OL", "OLE MEDIA MANAGEMENT LP");
    m.insert("OUT", "Outgivery");
    m.insert("PAC", "Waves Of Pacifica Music");
    m.insert("PAP", "Papi Capi Holland Publishing");
    m.insert("PBM", "Premiumbeat Uk");
    m.insert("PC", "Polygram Canada");
    m.insert("PEN", "Pen Music Group Inc");
    m.insert("PER", "Perfect Songs Ltd");
    m.insert("PFC", "Pigfactory Continental Ltd");
    m.insert("PFH", "Pennies From Heaven Bv");
    m.insert("PFM", "Pink Floyd Music Publishers LTD");
    m.insert("PG", "Universal - PolyGram Int. Publ., Inc.");
    m.insert("PGM", "Paulina Golba Music");
    m.insert("PIG", "PIGS RIOT PUBLISHING");
    m.insert("PLK", "Pelikan Muzik-Mmg Turk Yayimcilik");
    m.insert("PLM", "Picture Lock Music Library Limited");
    m.insert("PLS", "Pentagon Lipservices");
    m.insert("PM", "PEN Music Group, Inc.");
    m.insert("POS", "Position Music Publishing");
    m.insert("PPA", "These Are Songs Of Pulse");
    m.insert("PR", "PEERMUSIC (UK) LTD.");
    m.insert("PRL", "Preludio S R L");
    m.insert("PRM", "Paul Rodriguez Music Ltd");
    m.insert("PRO", "Nikolaos Oikonomou Protasis Music Publishing");
    m.insert("PSL", "Proof Songs Ltd");
    m.insert("PT", "Prime Time Productions LTD");
    m.insert("PTR", "Premier Ascap Tracks");
    m.insert("PU", "Pump audio publishing");
    m.insert("RAD", "Radio-Tele-Music-Belgie- Nederland");
    m.insert("RAL", "Raleigh Music Publishing Llc");
    m.insert("RAT", "Razor And Tie Music Publishing");
    m.insert("RBM", "Songs Of Red Bull");
    m.insert("REB", "Rebel Music Publishing");
    m.insert("RED", "Red Brick Music Publishing");
    m.insert("REF", "Reformation Publishing Co Ltd");
    m.insert("REL", "Reliable Source Music Limited");
    m.insert("RES", "Red Smoke B.V.");
    m.insert("RG", "Reach Global (Uk) Limited");
    m.insert("RHM", "Round Hill Works");
    m.insert("RHY", "Rhythmic Skeleton Music");
    m.insert("RIM", "Red Igloo Music");
    m.insert("RIS", "Ram Island Songs");
    m.insert("RM", "REVERB MUSIC");
    m.insert("RML", "Reverb Music Ltd");
    m.insert("RMM", "Reservoir Media Music");
    m.insert("RMP", "Reach Music Publishing Inc.");
    m.insert("RMW", "Spencer Jack Music");
    m.insert("RNL", "Routenote Limited");
    m.insert("RO", "Roba Music Verlag Gmbh");
    m.insert("ROS", "Rossio Music Publishing Lda");
    m.insert("RSM", "Schedler Rudi Musikverlag Gmbh");
    m.insert("RT", "SONGS OF RAZOR AND TIE");
    m.insert("RTM", "Reverb 2 Music LTD");
    m.insert("SA", "Sony/ATV Music Publishing LLC");
    m.insert("SAS", "Schwartz And Sons");
    m.insert("SAV", "Sirens Music Publishing Andrea Vitz");
    m.insert("SBI", "Shapiro Bernstein Spain");
    m.insert("SC1", "Scorpio Music");
    m.insert("SCI", "Super Cassettes Industries Ltd");
    m.insert("SCS", "Scandinavian Songs Ab");
    m.insert("SEN", "Sentric Music Limited");
    m.insert("SFB", "Songs Music Publishing Llc");
    m.insert("SFM", "Strange Fruit Music Publishing");
    m.insert("SGM", "SAREGAMA PLC");
    m.insert("SGR", "Soundgram");
    m.insert("SH", "SCHOTT MUSIC CORPORATION");
    m.insert("SID", "Sidomusic B Liechti Et Cie");
    m.insert("SIK", "Sikorski Hans Musikverlag Gmbh- Co");
    m.insert("SIL", "Silva Screen Music (Publishers) Ltd");
    m.insert("SIM", "Sidem Editions");
    m.insert("SLM", "Schacht Music U S Inc");
    m.insert("SLP", "Sounds Like Publishing Limited");
    m.insert("SM", "SANCTUARY MUSIC PUBLISHING LIMITED");
    m.insert("SMG", "Strengholt Musikverlag Gmbh");
    m.insert("SMN", "Sentric Music Net");
    m.insert("SMP", "Schubert Music Publishing Sp Z OO");
    m.insert("SMU", "Schedler Music Publishing Usa");
    m.insert("SMV", "Smv Schacht Musikverlage Gmbh&CoKg");
    m.insert("SNZ", "Sneakerz Muzik");
    m.insert("SOB", "Sob Audio Imaging Bv");
    m.insert("SOH", "Soho Production Music");
    m.insert("SOM", "Sonoton Music Gmbh Co Kg");
    m.insert("SON", "Ram Island Songs");
    m.insert("SOV", "Sovereign Society");
    m.insert("SP", "Seed Point Music Publishing Ltd");
    m.insert("SPI", "Spirit One Music");
    m.insert("SPM", "Spirit Services Holdings S A R L");
    m.insert("SRP", "Savile Row Publishing Bv");
    m.insert("SSM", "SMALL STONE MEDIA");
    m.insert("ST", "State One Musikverlag Gmbh");
    m.insert("STG", "Stiggy Music And Management Ab");
    m.insert("STM", "St Music Llc");
    m.insert("STO", "Stock Music International");
    m.insert("STR", "Strictly Confidential Suisse");
    m.insert("STV", "S A T V Publishing Ltd");
    m.insert("SUG", "Sugar-Melodi Inc");
    m.insert("SUH", "Sugar House Publishing");
    m.insert("SUM", "Sugarmusic");
    m.insert("TBO", "The Back Office");
    m.insert("TCP", "The Chief Music Publishing");
    m.insert("TEG", "THE ENTERTAINMENT GROUP BV");
    m.insert("TEP", "Tousensemble Publishing");
    m.insert("TFJ", "The Funky Junkies Music Company Ltd");
    m.insert("THI", "13 Music Limited");
    m.insert("TIM", "Bennett Coleman And Co Ltd");
    m.insert("TJM", "T J Musicservice Gmbh");
    m.insert("TLM", "Truelove Music Scandinavia");
    m.insert("TM", "Talpa Music Bv");
    m.insert("TMS", "The Missing Synch");
    m.insert("TOF", "Two One Five Music");
    m.insert("TPL", "Toolroom Publishing Limited");
    m.insert("TRN", "Tenyor Music");
    m.insert("TRP", "The Right People");
    m.insert("TSM", "Third Side Us Publishing");
    m.insert("TTD", "22D MUSIC US1");
    m.insert("TUB", "Maktub Music Publishing");
    m.insert("TUN", "Tunecore Digital Music");
    m.insert("ULT", "Ultra Empire Music");
    m.insert("UM", "Universal Musica, Inc.");
    m.insert("UMT", "Universal Muzik Taksim Edisyon AS");
    m.insert("UN", "Universal Music Publishing Ricordi Srl");
    m.insert("UPR", "UPRIGHT MUSIC APS");
    m.insert("USE", "Extrapolate Music");
    m.insert("UT", "Ultra Tunes");
    m.insert("VAM", "Velvet Apple Music");
    m.insert("VAN", "Van Mccoy Music Inc");
    m.insert("VFC", "Velocity Future Collections");
    m.insert("VM", "Vander Music Inc");
    m.insert("WAM", "Words And Music Worldwide");
    m.insert("WAR", "Warp Music Limited");
    m.insert("WB", "Warner/Chappell Music Publishing Limited");
    m.insert("WBX", "Wardlaw Banks Ltd");
    m.insert("WD", "Walt Disney Music (Usa) Co");
    m.insert("WIN", "Wintrup Musikverlage Walter Holzbaur");
    m.insert("WIX", "Wixen Music Uk Ltd");
    m.insert("WML", "WESTBURY MUSIC LTD");
    m.insert("WND", "Works Of Wonderlous");
    m.insert("WOM", "WEST ONE MUSIC LIMITED");
    m.insert("WP", "Windswept Pacific");
    m.insert("WWM", "New Thunder Music Co");
    m.insert("YL", "Yell Music Limited");
    m.insert("ZB", "Zomba Music Publishing");
    m.insert("ZMP", "Zodiak Music Publishing");
    m.insert("ZYX", "Zyx Uk Publishing Limited");
    m
});

/// Validates a society transmitter code exists in the lookup table
pub fn is_valid_transmitter_code(code: &str) -> bool {
    SOCIETY_TRANSMITTER_CODES.contains_key(code)
}

/// Gets the society name for a transmitter code
pub fn get_society_name_for_transmitter(transmitter_code: &str) -> Option<&'static str> {
    SOCIETY_TRANSMITTER_CODES.get(transmitter_code).copied()
}

/// Gets all valid transmitter codes
pub fn get_all_transmitter_codes() -> Vec<&'static str> {
    SOCIETY_TRANSMITTER_CODES.keys().copied().collect()
}
