[package]
name = "allegro_cwr"
version = "0.1.0"
edition = "2024"
description = "CWR (Common Works Registration) file parser library"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = "0.4"